# Generated by Django 4.0.3 on 2022-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_implmentation', '0004_user3mfacodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('accountNumber', models.CharField(max_length=11)),
                ('transactionAmount', models.CharField(max_length=10)),
                ('transactionType', models.CharField(max_length=100)),
            ],
        ),
    ]
